### PR TITLE
Fix warning on latest nightly

### PR DESCRIPTION
**Pull request by Amanieu**
This was causing CI to fail.

### CODE REVIEW

**Review by workingjubilee — APPROVED** [review]
I assume the continued failure on some platforms is intentional.

**Comment by Amanieu** [comment]
Yes, android CI is broken because of the libunwind changes (and has been broken for a while). I can have a go at fixing it though...

**Comment by workingjubilee** [comment]
That seems to be... less fixed, as it had 3 failures and now it has 5. Can you open an issue for the Android failures and then we can tag in the Android team?

**Comment by Amanieu** [comment]
Issue for Android CI: https://github.com/rust-lang/backtrace-rs/issues/531

**Comment by workingjubilee** [comment]
Thank you!

**Pull request merged**
