### PR TITLE
Add support for Miri backtraces

### PR DESCRIPTION
**Pull request by Aaron1011**
Companion to https://github.com/rust-lang/miri/pull/1559

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks reasonable to me, thanks for this! I figure it's probably best to wait for the companion PR to merge first before this?

**Comment by Aaron1011** [comment]
I think the PRs should be reviewed together, but this PR should be merged first. That will allow us to add Miri tests on the `backtrace-rs` side once a nightly with the new Miri is available.

**Comment by alexcrichton** [comment]
Ok seems reasonable to merge then, but looks like rustfmt is needed?

**Comment by Aaron1011** [comment]
Oops, I didn't realize which repository I was commenting on. I meant to say that the Miri PR should be merged first.

**Comment by alexcrichton** [comment]
Ah makes sense! If you can ping me when the upstream PR lands I'd be happy to merge this one!

**Comment by Aaron1011** [comment]
Unfortunately, the test suite does not currently pass under Miri, so the actual content of this PR isn't being tested by CI.

However, this PR can be tested locally by running a simple program (e.g. `println!("{:?}", backtrace::Backtrace::new())`) under Miri, and observing the output.

I plan to do some follow-up work to get the test suite passing under Miri.

**Comment by Aaron1011** [comment]
@alexcrichton The Miri PR had landed, so this PR is ready to be merged.

**Comment by alexcrichton** [comment]
Ok, thanks!

**Pull request merged**
