### PR TITLE
don't let rustc-dep-of-std enable backtrace-sys

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/backtrace-rs/issues/253

### CODE REVIEW

**Comment by alexcrichton** [comment]
I sort of forget the context for this at this point again, but is this somethign that we can condition the target string on? For example could a new target be added to print out the `empty` cfg? Or is this required as part of a build elsewhere or something like that?

**Comment by RalfJung** [comment]
The point of this is to be able to do a cross check build of libstd without the backtrace feature for foreign architectures with only a Rust toolchain. This is needed for https://github.com/rust-lang/miri/issues/1198: since Miri is just an interpreter, *in principle* we should be able to emulate any target platform on any host platform. Since recently Miri just does check builds for everything, so https://github.com/rust-lang/rust/issues/56443 is not a problem any more.

The only thing that still fails when I run `xargo-check check --target x86_64-apple-darwin` on my Linux box is that, even though the backtrace feature in libstd is disabled, libstd still depends on backtrace-sys (transitively) and its build script fails (as I have no apple toolchain and headers installed).

libstd without the backtrace feature depends on an "empty" backtrace with no features (you requested that in https://github.com/rust-lang/rust/pull/64444 to avoid lots of `cfg` in libstd). Unfortunately, due to cargo limitations, the fact that backtrace forwards the rustc-dep-of-std feature to backtrace-sys means that the rustc-dep-of-std backtrace feature implicitly enables backtrace-sys. So, that "empty" backtrace crate is actually not quite so empty when rustc-dep-of-std is enabled.

> is this somethign that we can condition the target string on

I don't follow... how would we condition the target string on anything? We don't control the target string?

**Comment by alexcrichton** [comment]
Ah ok that makes sense, thanks for the explanation!

The motivating case looks to be "I disabled backtraces in libstd but backtrace-sys is still getting built when checking for standard platforms", specifically in your cross build case. That's good enough for me at least :)

Ah and for conditioning the target string, I thought this was originally motivated by "whenever I build for platform X I want to disable backtraces" which I think is best handled in the code itself, not with more features. That's not the motivation for this, though, so it's all good!

**Comment by RalfJung** [comment]
> The motivating case looks to be "I disabled backtraces in libstd but backtrace-sys is still getting built when checking for standard platforms", specifically in your cross build case. 

Yes that's a good summary. :)

**Pull request merged**
