### PR TITLE
Avoid panicking on overflow due to bias wrapping

### LINKED ISSUE #329: gimli.rs: attempt to add with overflow
I experienced the following error after updating an application to use backtrace-rs v0.3.47:

- **Message:**  attempt to add with overflow
- **Location:** /builder/home/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.47/src/symbolize/gimli.rs:413

Which looks to be here:

https://github.com/rust-lang/backtrace-rs/blob/4578e94/src/symbolize/gimli.rs#L413

Unfortunately this error is occurring in a production build which consumes exclusive access to a hardware resource, so I wasn't able to dig into it much further beyond that.

It also hung if I tried to set `RUST_BACKTRACE` to either `1` or `full`, I assume because of the circular dependency of obtaining a backtrace in the event the backtrace code crashes...

~~I will double check I'm doing a release build as I'm a bit confused why the arithmetic is checked otherwise as it's not doing a `checked_add`.~~

Aha, this particular application enables checked arithmetic in release builds explicitly:

```toml
[profile.release]
overflow-checks = true
```

### PR DESCRIPTION
**Pull request by alexcrichton**
It's not entirely clear to me if this'll fix the issue, or why this
issue is coming up, but maybe some biases are negative in some systems?

Closes #329

### CODE REVIEW

**Comment by alexcrichton** [comment]
@tarcieri are you up for testing this out before it's merged/released? I'd like to confirm that it actually fixes the issue you're seeing. Additionally, if possible, would you be up for running a build with a bit more logging to try to dig into what's happening under the hood here?

**Comment by tarcieri** [comment]
@alexcrichton sure, I can do either of those

**Comment by alexcrichton** [comment]
Ok the first commit here in theory should fix the issue and the second commit should have some debug logging if you're ok testing that out

**Comment by tarcieri** [comment]
It's no longer crashing 🎉 

I'll follow up with the debug output separately.

**Comment by alexcrichton** [comment]
Thanks again for the assistance!

**Pull request merged**
