### PR TITLE
Finish up Miri integration

### PR DESCRIPTION
**Pull request by Aaron1011**
This PR gets all of the tests passing under Miri, and runs them on CI.

### CODE REVIEW

**Comment by Aaron1011** [comment]
@alexcrichton: How do you want to handle the case where Miri is not available for a given channel?

**Comment by alexcrichton** [comment]
Thanks for this! Could a new CI builder be added with a pinned nightly version to handle drift in miri?

**Comment by Aaron1011** [comment]
@RalfJung What's the preferred way to handle this kind of thing? Is there a way to get Rustup to automatically install the most recent nightly that has Miri available?

**Comment by RalfJung** [comment]
> Is there a way to get Rustup to automatically install the most recent nightly that has Miri available?

Yes, it is described in our README:
```
MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
rustup set profile minimal
rustup default "$MIRI_NIGHTLY"
rustup component add miri
```

**Comment by Aaron1011** [comment]
@alexcrichton: This should be ready to merge

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
