### PR TITLE
gimli: Enable backtrace for FreeBSD 

### LINKED ISSUE #325: Gimli doesn't support FreeBSD
I believe all that's necessary to support FreeBSD is to upstream a definition of `dl_iterate_phdr` into the `libc` crate, after that support should be as simple as updating [this line](https://github.com/rust-lang/backtrace-rs/blob/bb5aa64804d6ba83a768c7ed1c5d67435ddba53e/src/symbolize/gimli.rs#L270-L273).

### LINKED ISSUE #326: Gimli doesn't support OpenBSD
I believe all that's necessary to support OpenBSD is to upstream a definition of `dl_iterate_phdr` into the `libc` crate, after that support should be as simple as updating [this line](https://github.com/rust-lang/backtrace-rs/blob/bb5aa64804d6ba83a768c7ed1c5d67435ddba53e/src/symbolize/gimli.rs#L270-L273).

### PR DESCRIPTION
**Pull request by cemeyer**
#384 attempt number 2.

Closes #325.

### CODE REVIEW

**Comment by cemeyer** [comment]
It is just @lzutao's earlier PR, rebased over the uclibc merge conflict.

**Comment by alexcrichton** [comment]
Thanks! Is this ready to land with libc changes published?

**Comment by cemeyer** [comment]
Rust newbie — how would I find out?  On #384 lzutao mentioned:

> This doesn't block on libc anymore.

**Comment by alexcrichton** [comment]
To confirm, have you tested this on the platforms enabled here? If so I think the `libc` dependency's version should be bumped in this crate's version requirement because we'll require a newer version with the bindings.

**Comment by cemeyer** [comment]
I have not. I can test on FreeBSD but I don’t have any of the other systems. Would that just be `cargo test`, or any additional manual testing? I can bump the libc requirement in cargo.toml.  Thanks!

**Comment by alexcrichton** [comment]
Yes a `cargo test` wouold be great. I'm hesitant to enable platforms here unless they've been tested since this switch likely pulls in a big chunk of code.

**Comment by cemeyer** [comment]
> Yes a `cargo test` wouold be great.

Ok, that was fast.  I think I must have already run it.  It passes.  However, I think the tests may need platform adjustment as well to actually cover this change.  Give me a few minutes...

> I'm hesitant to enable platforms here unless they've been tested since this switch likely pulls in a big chunk of code.

They're tier 2+ platforms, right?  I'm worried we might be applying higher scrutiny to restoring functionality that was lost in rust 1.47 than we were in losing it in the first place.  At the same time, I don't feel strongly about Open/NetBSD support and am ok dropping them if you insist.

**Comment by alexcrichton** [comment]
My main goal is that if you're explicitly affecting new targets in this PR there should at least be confidence that the code compiles. It doesn't sound like you're checking that for all the platforms listed here? I would ideally like confirmation that the tests work with this PR. If there are other bugs then they should be filed as new issues.

**Comment by cemeyer** [comment]
Ok, I’ll drop the non-FreeBSD diff. Cargo test passes.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by cemeyer** [comment]
Thank you! :-)

**Pull request merged**
