### PR TITLE
deps: update miniz_oxide to 0.7

### PR DESCRIPTION
**Pull request by poliorcetics**
I don't think this change the MSRV but I haven't really checked.

Could a new release be done with this too ?

### CODE REVIEW

**Comment by JohnTitor** [comment]
Unfortunately it breaks MSRV (it'd become 1.46) but I think it's old enough to do so: https://github.com/rust-lang/rust/pull/72437

**Comment by poliorcetics** [comment]
Sorry for the delay on this, hopefully I didn't miss anything when updating MSRV

**Comment by poliorcetics** [comment]
> `   = note: ld: error: unable to find library -lunwind`

I don't know what's needed for this to work for android

**Comment by MarijnS95** [comment]
> > `   = note: ld: error: unable to find library -lunwind`
> 
> I don't know what's needed for this to work for android

That also happens on `master`, fwiw :)

**Review by JohnTitor — APPROVED** [review]
LGTM but I'd like to wait for someone else to approve the MSRV bump.

**Comment by poliorcetics** [comment]
I’ll remove my test commits for android tomorrow, I was trying to fix the compilation issue but it didn’t work, no need to keep them

**Comment by poliorcetics** [comment]
MSRV was updated to 1.55 on master so I don't need to upgrade it in this MR anymore :)

**Pull request merged**
