### PR TITLE
remove some instances of dead_code

### PR DESCRIPTION
**Pull request by klensy**

### CODE REVIEW

**Comment by klensy** [comment]
> Code size changes for a hello-world Rust program linked with libstd with backtrace:
> 
> On platform `ubuntu-latest`:
> 
>     * Original binary size: **362,912 B**
> 
>     * Updated binary size: **362,920 B**
> 
>     * Difference: **8 B** (0%)

Super weird results.

**Comment by klensy** [comment]
Anyway, second commit reduces `Frame` size:
```
print-type-size type: `capture::Frame`: 40 bytes, alignment: 8 bytes
print-type-size     discriminant: 8 bytes
print-type-size     variant `Raw`: 32 bytes
print-type-size         field `.0`: 32 bytes
print-type-size     variant `Deserialized`: 32 bytes
print-type-size         field `.ip`: 8 bytes
print-type-size         field `.symbol_address`: 8 bytes
print-type-size         field `.module_base_address`: 16 bytes


print-type-size type: `capture::Frame`: 32 bytes, alignment: 8 bytes
print-type-size     variant `Raw`: 32 bytes
print-type-size         field `.0`: 32 bytes
```

**Comment by workingjubilee** [comment]
Thanks!

I'll take a reduction in the actual data structure size yeah, binary size doesn't matter much.

**Review by workingjubilee — APPROVED** [review]
Thanks!

**Pull request merged**
