### PR TITLE
very good new binary size improvement

### PR DESCRIPTION
**Pull request by Noratrieb**
this significantly improves binary size, we need to merge this ASAP

### CODE REVIEW

**Comment by Nilstrieb** [comment]
let me regress binary size to test this

**Comment by workingjubilee** [comment]
slightly concerned that this may not actually work unless the changeset is on master due to the jank way GHA works.

**Comment by Nilstrieb** [comment]
ugh, it does! `pull_request_target` does that.

**Comment by Nilstrieb** [comment]
i can open a new PR for just the first commit to merge

**Comment by workingjubilee** [comment]
yeah I am happy to optimistically merge that change.

**Comment by Nilstrieb** [comment]
```
{"platform":"ubuntu-latest","reference":"350632","updated":"350632"}
{"platform":"windows-latest","reference":"135168","updated":"135168"}
```
either I'm bad at regression binary size or getting it from `stage0` doesn't quite work correctly and we really do need `stage0-sysroot` instead. I'm not very sure about that, who gets what from where when.

**Comment by workingjubilee** [comment]
@Kobzol whoops.

**Comment by Kobzol** [comment]
I think that we need to use `stage0-sysroot` (but first, it needs to be fixed). `stage0-sysroot` isn't actually used almost anywhere, so that's probably the reason why this wasn't noticed.

**Pull request closed without merging**
